//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucVuAdmin
    {
        public ChucVuAdmin()
        {

            this.tblAdmin01 = new HashSet<tblAdmin01>();
        }
    
        public int MaCV { get; set; }
        public string TenCV { get; set; }
    
        public virtual ICollection<tblAdmin01> tblAdmin01 { get; set; }
    }
}
