//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_SuDungDV
    {
        public int MaDV { get; set; }
        public int MaDDP { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual DonDatPhong DonDatPhong { get; set; }
    }
}
