//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatPhong()
        {
            this.CT_SuDungDV = new HashSet<CT_SuDungDV>();
        }
    
        public int MaDDP { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaP { get; set; }
        public Nullable<System.DateTime> NgayDen { get; set; }
        public Nullable<System.DateTime> NgayDi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaTinhTrang { get; set; }
        public Nullable<int> IDTaiKhoan { get; set; }
        public Nullable<decimal> TienPhong { get; set; }
        public Nullable<decimal> TienDichVu { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_SuDungDV> CT_SuDungDV { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual tblAdmin01 tblAdmin01 { get; set; }
        public virtual TT_DonDatPhong TT_DonDatPhong { get; set; }
    }
}
