//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatPhong
    {
        public int MaDDP { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaP { get; set; }
        public Nullable<System.DateTime> NgayDen { get; set; }
        public Nullable<System.DateTime> NgayDi { get; set; }
        public Nullable<decimal> TienCoc { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaTinhTrang { get; set; }
        public Nullable<int> IDTaiKhoan { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual TT_DonDatPhong TT_DonDatPhong { get; set; }
        public virtual tblAdmin01 tblAdmin01 { get; set; }
    }
}
