//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.DonDatPhong = new HashSet<DonDatPhong>();
        }
    
        public int MaKH { get; set; }
        public string TenKH { get; set; }
        public string Sdt { get; set; }
        public string Email { get; set; }
        public string CCCD { get; set; }
        public string QuocGia { get; set; }
        public string DiaChi { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
    
        public virtual ICollection<DonDatPhong> DonDatPhong { get; set; }
    }
}
