//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiPhong
    {
        public LoaiPhong()
        {
            this.Phong = new HashSet<Phong>();
        }
    
        public int MaLP { get; set; }
        public string TenLP { get; set; }
        public string MoTa { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        public virtual ICollection<Phong> Phong { get; set; }
    }
}
