//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_DonDatPhong
    {
        public TT_DonDatPhong()
        {
            this.DonDatPhong = new HashSet<DonDatPhong>();
        }
    
        public int MaTinhTrang { get; set; }
        public string TenTinhTrang { get; set; }
    
        public virtual ICollection<DonDatPhong> DonDatPhong { get; set; }
    }
}
